```{r libraries-data, message = F, warning = F}
# libraries and data
library(tidyverse)
library(scales)
library(ggridges)
library(patchwork)
bbdata <- read_csv("data/bbdata.csv")
```

```{r}
col4 <- c("#E06060", "#FFBFBF", "#E7F9FF", "#95D2EC")
col5 <- c("#E06060", "#FFBFBF", "#E7F9FF", "#95D2EC", "#47ABD8")

bb <- bbdata |>
  mutate(
    placement_bucket = case_when(
      placement_rank_percent < .09 ~ "Winner",
      placement_rank_percent <= .25 ~ "Late Game",
      placement_rank_percent <= .5 ~ "Upper Middle",
      placement_rank_percent <= .75 ~ "Lower Middle",
      placement_rank_percent <= 1 ~ "Early Out"
    ),
    wins_bucket = case_when(
      wins_rank_percent <= .25 ~ "Top Quartile",
      wins_rank_percent <= .5 ~ "High Quartile",
      wins_rank_percent <= .75 ~ "Low Quartile",
      wins_rank_percent <= 1 ~ "Bottom Quartile"
    ),
    age_bucket = case_when(
      age <= 29 ~ "19-29",
      age <= 39 ~ "30-39",
      age <= 80 ~ "40+"
    ))

bb$placement_bucket <- ordered(bb$placement_bucket,
                                 levels = c("Early Out",
                                            "Lower Middle",
                                            "Upper Middle",
                                            "Late Game",
                                            "Winner"))

bb$wins_bucket <- ordered(bb$wins_bucket,
                                 levels = c("Bottom Quartile",
                                            "Low Quartile",
                                            "High Quartile",
                                            "Top Quartile"))

bb$age_bucket <- ordered(bb$age_bucket,
                                 levels = c("19-29",
                                            "30-39",
                                            "40+"))
```

```{r}
bb_bipoc_place <- bb |>
  group_by(BIPOC, placement_bucket) |>
  summarize(n = n()) |>
  mutate(freq = n / sum(n)) |>
  mutate(per = label_percent(accuracy = 1)(freq)) |>
  ungroup()

bb_lgbt_place <- bb |>
  group_by(LGBT, placement_bucket) |>
  summarize(n = n()) |>
  mutate(freq = n / sum(n)) |>
  mutate(per = label_percent(accuracy = 1)(freq)) |>
  ungroup()

bb_gender_place <- bb |>
  group_by(gender, placement_bucket) |>
  summarize(n = n()) |>
  mutate(freq = n / sum(n)) |>
  mutate(per = label_percent(accuracy = 1)(freq)) |>
  ungroup()

bb_age_place <- bb |>
  group_by(age_bucket, placement_bucket) |>
  summarize(n = n()) |>
  mutate(freq = n / sum(n)) |>
  mutate(per = label_percent(accuracy = 1)(freq)) |>
  ungroup()

bb_gender_wins <- bb |>
  group_by(gender, wins_bucket) |>
  summarize(n = n()) |>
  mutate(freq = n / sum(n)) |>
  mutate(per = label_percent(accuracy = 1)(freq)) |>
  ungroup()

bb_age_wins <- bb |>
  group_by(age_bucket, wins_bucket) |>
  summarize(n = n()) |>
  mutate(freq = n / sum(n)) |>
  mutate(per = label_percent(accuracy = 1)(freq)) |>
  ungroup()

bipoc_place <-
  ggplot(bb_bipoc_place, aes(y = BIPOC, x = freq, label = per, fill = placement_bucket)) +
  geom_col(position = "fill") +
  geom_text(size = 3, fontface = "bold", family = "Times New Roman",
            position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = col5) +
  labs(fill = "") +
  theme_void() +
  theme(axis.title.y = element_text(face = "bold"),
        axis.text.y = element_text(),
        text = element_text(family = "Times New Roman"))

lgbt_place <-
  ggplot(bb_lgbt_place, aes(y = LGBT, x = freq, label = per, fill = placement_bucket)) +
  geom_col(position = "fill") +
  geom_text(size = 3, fontface = "bold", family = "Times New Roman",
            position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = col5) +
  labs(fill = "") +
  theme_void() +
  theme(axis.title.y = element_text(face = "bold"),
        axis.text.y = element_text(),
        text = element_text(family = "Times New Roman"))

gender_place <-
  ggplot(bb_gender_place, aes(y = gender, x = freq, label = per, fill = placement_bucket)) +
  geom_col(position = "fill") +
  geom_text(size = 3, fontface = "bold", family = "Times New Roman",
            position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = col5) +
  labs(y = "Gender", fill = "") +
  theme_void() +
  theme(axis.title.y = element_text(face = "bold"),
        axis.text.y = element_text(),
        text = element_text(family = "Times New Roman"))

age_place <-
  ggplot(bb_age_place, aes(y = age_bucket, x = freq, label = per, fill = placement_bucket)) +
  geom_col(position = "fill") +
  geom_text(size = 3, fontface = "bold", family = "Times New Roman",
            position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = col5) +
  labs(y = "Age", fill = "") +
  theme_void() +
  theme(axis.title.y = element_text(face = "bold"),
        axis.text.y = element_text(),
        text = element_text(family = "Times New Roman"))

gender_wins <-
  ggplot(bb_gender_wins, aes(y = gender, x = freq, label = per, fill = wins_bucket)) +
  geom_col(position = "fill") +
  geom_text(size = 3, fontface = "bold", family = "Times New Roman",
            position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = col4) +
  labs(y = "Gender", fill = "") +
  theme_void() +
  theme(axis.title.y = element_text(face = "bold"),
        axis.text.y = element_text(),
        text = element_text(family = "Times New Roman"))

age_wins <-
  ggplot(bb_age_wins, aes(y = age_bucket, x = freq, label = per, fill = wins_bucket)) +
  geom_col(position = "fill") +
  geom_text(size = 3, fontface = "bold", family = "Times New Roman",
            position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = col4) +
  labs(y = "Age", fill = "") +
  theme_void() +
  theme(axis.title.y = element_text(face = "bold"),
        axis.text.y = element_text(),
        text = element_text(family = "Times New Roman"))
```

```{r}
(bipoc_place / lgbt_place / gender_place / age_place) +
  plot_layout(guides = "collect", heights = c(1, 1, 1, 1.33)) &
  theme(legend.position = "top")

(gender_wins / age_wins) +
  plot_layout(guides = "collect", heights = c(1, 1.33)) &
  theme(legend.position = "top")
```

```{r}
bipoc_place_time <- bb |>
  filter(BIPOC == "Y") |>
  select(first, season_code, placement_bucket) |>
  arrange(season_code) |>
  mutate(n = 1, cumul = cumsum(n),
         lategame = if_else(placement_bucket %in% c("Late Game", "Winner"), "Y", "N")) |>
  group_by(season_code) |>
  mutate(cumul = max(cumul), cnt = sum(lategame == "Y")) |>
  slice(1) |>
  ungroup() |>
  mutate(cumul_lategame = cumsum(cnt), cumul_perc = cumul_lategame / cumul)

bipoc_place_time_annot <-
"CBS Introduces 50%
BIPOC Initiative"

ggplot(bipoc_place_time, aes(x = season_code, y = cumul_lategame)) +
  geom_line(color = col5[5], linewidth = 2) +
  annotate("text", x = 19, y = 20, label = bipoc_place_time_annot, family = "Times New Roman") + 
  geom_vline(xintercept = 22.5, linetype = "dashed", linewidth = 1.5) +
  labs(y = "Cum. Num of BIPOC HGs in Late-Game",
       x = "Season Number") +
  theme_bw() +
  theme(text = element_text(family = "Times New Roman", size = 14),
        panel.grid = element_blank())
```

```{r}
gen_wins_time <- bb |>
  select(first, season_code, gender, total_wins) |>
  group_by(season_code) |>
  mutate(numcomps = sum(total_wins)) |>
  group_by(season_code, gender) |>
  mutate(numwins_gen = sum(total_wins)) |>
  filter(gender == "F") |>
  slice(1) |>
  ungroup() |>
  mutate(perc_women_wins = numwins_gen / numcomps * 100)

ggplot(gen_wins_time, aes(x = season_code, y = perc_women_wins)) +
  geom_hline(yintercept = 50, linewidth = 1.2) +
  annotate("text", x = 23, y = 52, label = "Equitable Scenario", family = "Times New Roman") + 
  geom_line(color = col5[4], linewidth = 0.7, linetype = "dashed") +
  geom_point(color = col5[5], size = 3) +
  labs(y = "% of Comps Won by Women",
       x = "Season") +
  theme_bw() +
  theme(text = element_text(family = "Times New Roman", size = 14),
        panel.grid = element_blank())
```

